
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 20 22:37:34 COT 2021
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 15;
  public static final int Parentesis_a = 14;
  public static final int Suma = 8;
  public static final int Numero = 18;
  public static final int ERROR = 19;
  public static final int Identificador = 17;
  public static final int Comillas = 4;
  public static final int Coma = 12;
  public static final int P_coma = 16;
  public static final int T_dato = 5;
  public static final int Cadena = 6;
  public static final int EOF = 0;
  public static final int Division = 11;
  public static final int Resta = 9;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Punto = 13;
  public static final int Igual = 7;
  public static final int Multiplicacion = 10;
  public static final int leer = 3;
}

