
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 20 22:56:23 COT 2021
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 16;
  public static final int muestrar = 4;
  public static final int Parentesis_a = 15;
  public static final int Suma = 9;
  public static final int Numero = 19;
  public static final int ERROR = 20;
  public static final int Identificador = 18;
  public static final int Comillas = 5;
  public static final int Coma = 13;
  public static final int P_coma = 17;
  public static final int T_dato = 6;
  public static final int Cadena = 7;
  public static final int EOF = 0;
  public static final int Division = 12;
  public static final int Resta = 10;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Punto = 14;
  public static final int Igual = 8;
  public static final int Multiplicacion = 11;
  public static final int leer = 3;
}

